### PR TITLE
Only allow ActiveModel under 5 because of v5's Ruby 2.2 requirement &…

### PR DESCRIPTION
**Pull request by minimul**
… Fix links from PR #325

### CODE REVIEW

**Comment by kmeister2000** [comment]
Out of curiosity, what's the plan for supporting Rails 5 / ActiveModel v5?  I was in the process of updating my app.  Is there a list of specific work that needs to be done that I could look at and possibly help with?

**Comment by ruckus** [comment]
@kmeister2000 I dont have any Rails 5 apps so I haven't even tried to run this gem in Rails 5 to know if there are any issues (?). If you encounter issues during your upgrade please log them here. Thanks!

**Comment by minimul** [comment]
With the new commits quickbooks-ruby should bundle install now on Rails 5.
Of course, you have to point at master as we haven't pushed a new gem
version yet.

**Comment by drewish** [comment]
Oh... I just pulled master in to test out my PR for the rate limiting error and ran into this change trying to do a bundle update. I've been using it with Rails 5 in an application we're still developing and haven't noticed any issues yet. 

It's not clear to me why you're blocking use with ActiveRecord 5. Is it just the ruby 2.2 requirement? Is that breaking automated tests or something?

**Comment by minimul** [comment]
Yep - Ruby 2.2 is breaking the specs. We support Ruby > 1.9.3.
On Fri, Oct 28, 2016 at 11:12 AM, andrew morton <notifications@github.com> wrote:

> from: andrew morton <notifications@github.com>
> date: Fri, Oct 28 08:12 AM -07:00 2016
> to: ruckus/quickbooks-ruby <quickbooks-ruby@noreply.github.com>
> cc: Christian Pelczarski <zarski@gmail.com>, State change <state_change@noreply.github.com>
> reply-to: ruckus/quickbooks-ruby <reply@reply.github.com>
> subject: Re: [ruckus/quickbooks-ruby] Only allow ActiveModel under 5 because of v5's Ruby 2.2 requirement &… (#328)
> 
> Oh... I just pulled master in to test out my PR for the rate limiting error and ran into this change trying to do a bundle update. I've been using it with Rails 5 in an application we're still developing and haven't noticed any issues yet. 
> 
> It's not clear to me why you're blocking use with ActiveRecord 5. Is it just the ruby 2.2 requirement? Is that breaking automated tests or something?
> 
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/ruckus/quickbooks-ruby/pull/328#issuecomment-256947312


Regards — Christian

**Comment by drewish** [comment]
I stuck a commit on https://github.com/ruckus/quickbooks-ruby/pull/339 that makes the ActiveRecord gem version conditional on the Ruby version.

**Comment by drewish** [comment]
@minimul yeah there's really no reason you can't support both. give https://github.com/ruckus/quickbooks-ruby/pull/339/commits/7ed9b701c93b7877f61152dfb54fc35951b2dd0c a look.

**Pull request merged**
