### PR TITLE
Changed the initialize method of BaseReference model

### PR DESCRIPTION
**Pull request by divyak-eligibleapi**
Related to https://github.com/ruckus/quickbooks-ruby/issues/253

Divyas-MacBook-Pro:quickbooks-ruby divyakesapragada$ git push origin master
Counting objects: 20, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (20/20), done.
Writing objects: 100% (20/20), 3.18 KiB | 0 bytes/s, done.
Total 20 (delta 14), reused 0 (delta 0)
To git@github.com:divyak-eligibleapi/quickbooks-ruby.git
   6c46373..dc2dedc  master -> master
Divyas-MacBook-Pro:quickbooks-ruby divyakesapragada$ bundle exec rspec spec
..................................................................................................................................................................................................................................................................................................................................................................

Finished in 1.73 seconds
354 examples, 0 failures
Coverage report generated for RSpec to /workspace/quickbooks-ruby/coverage. 2518 / 2634 LOC (95.6%) covered.

### CODE REVIEW

**Comment by minimul** [comment]
I like this PR but it appears to break `Quickbooks::Model::BaseReference.new(1)`.

We are going to have to support that "old" way of initializing BaseReference.

**Comment by divyak-eligibleapi** [comment]
@minimul added backwards compatibility

**Comment by ruckus** [comment]
Rather than make the whole argument a hash I think it makes more sense to make the `Id` parameter required and the other fields optional since that more closely resembles reality: the Id is required and the bare minimum and the name/type parameters are extra meta-data.

So the signature might look like:

`def initialize(id, options = {})`

and invocation would look like:

`Quickbooks::Model::BaseReference.new(1, name: "FedEx", value: "FexEx")`

Thoughts?

**Comment by minimul** [comment]
@ruckus Yup, well said. 

@divyak-eligibleapi Would you implement `def initialize(id, options = {})` ?

**Comment by divyak-eligibleapi** [comment]
sure makes sense.

**Comment by minimul** [comment]
Specs failing.

**Comment by divyak-eligibleapi** [comment]
yes i will check and update. got busy with some work. will update it today.

**Comment by divyak-eligibleapi** [comment]
@ruckus @minimul fixed the issue that was causing specs failure. can you please check now?

**Comment by ruckus** [comment]
Great, thank you!

**Pull request merged**
