### PR TITLE
Report service and model

### PR DESCRIPTION
**Pull request by raksonibs**

### CODE REVIEW

**Comment by raksonibs** [comment]
@minimul Does anyone know whether connecting to quickbooks offline also can be done through QBO? Say if a client only has the offline software?

**Comment by minimul** [comment]
I assume you mean QuickBooks Desktop? If so then no you need to use the QBSDK to get integrated. A good place to start is @ruckus article http://ruckus.tumblr.com/post/88152229186/rails-quickbooks-web-connector-qwc

**Comment by ChrisMagellan** [comment]
Guys, what's the status of this pull request right now? Is there anything I can help with? I need Report support pretty badly!

**Comment by ruckus** [comment]
Merged. I'll release a gem update shortly.

**Comment by ruckus** [comment]
`0.2.3` has been released

**Comment by ChrisMagellan** [comment]
Thanks!

**Comment by nasy** [comment]
Hi guys,

The links on the Reports API section are broken. It would be good to have some examples. I managed to get a report but i get an xml response which is not very friendly. Any chance to get a JSON? This is my code:

    service = Quickbooks::Service::Reports.new
    service.company_id = 1234
    service.access_token = 1234
    @result = service.query('BalanceSheet')
    @resultXML = service.last_response_xml
puts YAML::dump(@result)
puts YAML::dump(@resultXML.inspect)

**Comment by ruckus** [comment]
hi @nasy I've updated the links in the README - thanks for pointing that out.

Unfortunately at this time this library only uses XML and support for JSON is on the distant horizon.

**Comment by nasy** [comment]
hi @ruckus , thanks for fixing the links. 

I managed to get the XML but I am struggling to parse it.
I want to get the report name for example.

< Report xmlns="http://schema.intuit.com/finance/v3" >
< Header >
< Time>2015-09-11T06:05:35-07:00</ Time >
< ReportName >BalanceSheet</ ReportName >
.... (continues)

So I do 

@resultXML = service.last_response_xml

  xml = Nokogiri::XML(@resultXML)
  puts "#XML#"
  puts xml
  block = xml.xpath("//ReportName")
  puts "#CLASS#"
  puts block.text
  puts block.class

And this is the response, I can't get the "BalanceSheet" value? Any ideas?

#XML#
<?xml version="1.0"?>
#CLASS#

Nokogiri::XML::NodeSet

**Comment by Craggar** [comment]
Here's what I do, it might help:

```
doc = Nokogiri::XML(report.to_s)

    header = doc.at_css "Header"
    if header
      headerObject = {}
      headerObject[:time] = getXMLText(header, "Time")
      headerObject[:name] = getXMLText(header, "ReportName")
      headerObject[:basis] = getXMLText(header, "ReportBasis")
      headerObject[:start_date] = getXMLText(header, "StartPeriod")
      headerObject[:end_date] = getXMLText(header, "EndPeriod")
      headerObject[:summarize_columns_by] = getXMLText(header, "SummarizeColumnsBy")
      headerObject[:currency] = getXMLText(header, "Currency")
...etc...
```

**Comment by minimul** [comment]
You don't need to do the `@resultXML = service.last_response_xml` bit.

The `@result = service.query('BalanceSheet')` will return a `Quickbooks::Model::Report`, which
exposes the `.xml` method that yields a `Nokogiri::XML::Document`.

In short you do:
```
@result = service.query('BalanceSheet')
@result.xml.xpath() # or the much better query lang. IMHO .css()
```

**Comment by nasy** [comment]
Great, that worked perfectly. Thanks

 Code:

result = service.query('BalanceSheet')
puts YAML::dump(@result.xml.css("ReportName").text)

Result:

BalanceSheet

**Comment by ratbeard** [comment]
Note that if you do use xpath, you need to either include namespaces in your queries or a little easier is to remove them before calling xpath with: `report.xml.remove_namespaces!`.

Querying by css adds in the namespaces for you behind the scenes.

**Comment by nasy** [comment]
Hi again, sorry to ask again but I can't find any useful documentation about this,

I have been trying to get "Total Income" value but I am really struggling  

This is the XML "ProfitAndLoss"

<Report xmlns="http://schema.intuit.com/finance/v3">
<Header>...</Header>
<Columns>...</Columns>
<Rows>
<Row type="Section" group="Income">
<Header>
<ColData value="Income"/>
<ColData value=""/>
</Header>
<Rows>...</Rows>
<Summary>
<ColData value="Total Income"/>
<ColData value="391.25"/>
</Summary>
</Row>

I am using css to get the main "Report" node then want to iterate the rows until the Summary children value equals 'Total Income'. However 

profit_and_loss = service.query('ProfitAndLoss')
coll = profit_and_loss.xml.css("Report")

coll.css("Rows").children.each do |row|
 
            puts row.css("Summary").children[1]['value'].to_i # This prints other values

             if row.css("Summary").children[0]['value'] == 'Total Income'
		 puts 'Found it!' # Never gets here
 	     end
 end

This prints other deeper nodes like "Total Legal & Professional Fees" but does not find the 'Total Income'. Am i missing something?

**Comment by minimul** [comment]
Try
```
if row.css("Summary").first_element_child['value']
```
or
```
if row.css("Summary").first.elements[0]['value']
```
or
```
if row.at("Summary").elements[0]['value']
```
I always use "elements" instead of children in Nokogiri because it works more like what you would
expect children to work like.

**Comment by nasy** [comment]
Thanks @minimul but that didn't quite work for me. 

I noticed that I was missing an extra loop so I added "row.css("Summary").each do |sum|" and now it gets me all the values. Pasting the final code just in case somebody else needs it.

	@profit_and_loss = service.query('ProfitAndLoss', {}, filters)
		coll = @profit_and_loss.xml.css("Report")
		coll.css("Rows").children.each do |row|

				row.css("Summary").each do |sum|

						unless sum.children[0].nil? && sum.children[1].nil?

								if sum.children[1]
										puts '# #########'
										puts sum.children[0]['value']
										puts sum.children[1]['value']
										puts '# #########'

**Pull request closed without merging**
