### PR TITLE
Add ability to download PDF of a Payment

### PR DESCRIPTION
**Pull request by anaulin**
I followed the pattern that had already been established in the `Invoice` and `SalesReceipt` services.

### CODE REVIEW

**Comment by ruckus** [comment]
Thank you!

**Comment by anaulin** [comment]
@ruckus do you know if/when there will be a new minor version release that might include this change?

**Comment by ruckus** [comment]
Hi @anaulin thanks for the reminder; I just released `1.0.21` with your PR. Thanks!

**Comment by anaulin** [comment]
@ruckus Thank you! I appreciate how responsive you are. 😻

**Pull request merged**
