### PR TITLE
Send Invoice via Email

### PR DESCRIPTION
**Pull request by kirley**
@ruckus - This code implements the send invoice functionality:

https://developer.intuit.com/docs/api/accounting#/send-an-invoice

Usage:

```ruby
# send invoice to billing_email_address
sent_invoice = @invoice_service.send(invoice)
# send invoice to new address
sent_invoice = @invoice_service.send(invoice, "new@email.com")
```

Please let me know if you have any questions, i'd be happy to make any changes you'd like so that this can be merged in.

### CODE REVIEW

**Comment by minimul** [comment]
Looks good.

**Comment by ruckus** [comment]
Hi @kirley - thank you so much! One small request: can you please update the README? How about adding a section titled something like "Sending Invoice Emails" with your example. Thanks again!

**Comment by kirley** [comment]
Added a section of code to the readme as you requested.

**Comment by ruckus** [comment]
Fantastic, thank you so much.

**Pull request merged**
